begin;
-- P24: server-side throttling and revocable sensitive sessions.
create table private.security_events(id bigint generated always as identity primary key,user_id uuid,tenant_id uuid,event_type text not null,ip_hash text,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table private.rate_limits(bucket text not null,subject_hash text not null,window_start timestamptz not null,count integer not null default 1,primary key(bucket,subject_hash,window_start));
create table private.session_revocations(user_id uuid primary key references auth.users(id),revoked_after timestamptz not null default now(),reason text not null);
alter table private.security_events enable row level security;alter table private.rate_limits enable row level security;alter table private.session_revocations enable row level security;revoke all on private.security_events,private.rate_limits,private.session_revocations from public,anon,authenticated;
-- P26: advisor work queue without financial authority.
create view public.advisor_work_queue with(security_invoker=true) as select r.tenant_id,r.id repair_id,r.device,r.status,r.created_at,c.name customer_name,c.phone customer_phone from public.repairs r join public.customers c on c.tenant_id=r.tenant_id and c.id=r.customer_id where r.status in('created','waiting_parts','completed');
grant select on public.advisor_work_queue to authenticated;
-- P27: recoverable operation journal for ambiguous client outcomes.
create table public.operation_receipts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,operation_id uuid not null,kind text not null,status text not null check(status in('received','committed','failed','unknown')),resource_id uuid,error_code text,created_by uuid not null references auth.users(id),updated_at timestamptz not null default now(),unique(tenant_id,operation_id));
alter table public.operation_receipts enable row level security;revoke all on public.operation_receipts from public,anon,authenticated;grant select on public.operation_receipts to authenticated;create policy operation_receipts_read on public.operation_receipts for select to authenticated using(created_by=auth.uid() or private.has_role(tenant_id,array['admin']));
-- P30: integrations exist as disabled adapters until D10 is approved.
create table public.integration_adapters(id uuid primary key default gen_random_uuid(),tenant_id uuid,provider text not null,capability text not null,status text not null default 'disabled' check(status in('disabled','configured','active','error')),config_public jsonb not null default '{}',credentials_ref text,updated_at timestamptz not null default now(),unique(tenant_id,provider,capability));
alter table public.integration_adapters enable row level security;revoke all on public.integration_adapters from public,anon,authenticated;grant select on public.integration_adapters to authenticated;create policy adapters_read on public.integration_adapters for select to authenticated using((tenant_id is null and private.is_platform_admin()) or (tenant_id is not null and private.has_role(tenant_id,array['admin'])));
create function private.guard_rate_limit(p_bucket text,p_subject text,p_limit integer,p_window_seconds integer) returns boolean language plpgsql security definer set search_path='' as $$declare v_start timestamptz;v_count integer;begin if p_limit<1 or p_window_seconds<1 then return false;end if;v_start:=to_timestamp(floor(extract(epoch from now())/p_window_seconds)*p_window_seconds);insert into private.rate_limits(bucket,subject_hash,window_start,count)values(p_bucket,encode(extensions.digest(p_subject,'sha256'),'hex'),v_start,1)on conflict(bucket,subject_hash,window_start)do update set count=private.rate_limits.count+1 returning count into v_count;return v_count<=p_limit;end$$;
revoke all on function private.guard_rate_limit(text,text,integer,integer) from public,anon,authenticated;
commit;
