begin;
-- P13/P14: immutable ledger; allocations determine balance; reversals compensate.
create table public.obligations(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,repair_id uuid,kind text not null check(kind in('repair','sale','saas')),amount_minor bigint not null check(amount_minor>0),currency text not null default 'COP',status text not null default 'open' check(status in('open','settled','void')),created_at timestamptz not null default now(),unique(tenant_id,id));
create table public.ledger_entries(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,kind text not null check(kind in('charge','payment','reversal','courtesy')),amount_minor bigint not null check(amount_minor>0),method text,reference text,request_id uuid not null,created_by uuid not null references auth.users(id),reverses_id uuid references public.ledger_entries(id),created_at timestamptz not null default now(),unique(tenant_id,id),unique(tenant_id,request_id));
create table public.ledger_allocations(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,entry_id uuid not null,obligation_id uuid not null,amount_minor bigint not null check(amount_minor>0),unique(entry_id,obligation_id),foreign key(tenant_id,entry_id) references public.ledger_entries(tenant_id,id),foreign key(tenant_id,obligation_id) references public.obligations(tenant_id,id));
-- P15/P16 inventory and sale facts.
create table public.inventory_items(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,sku text not null,name text not null,stock integer not null default 0 check(stock>=0),reserved integer not null default 0 check(reserved>=0 and reserved<=stock),version integer not null default 1,unique(tenant_id,id),unique(tenant_id,sku));
create table public.inventory_movements(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,item_id uuid not null,kind text not null check(kind in('receive','reserve','release','consume','adjust')),quantity integer not null check(quantity<>0),request_id uuid not null,repair_id uuid,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),unique(tenant_id,request_id),foreign key(tenant_id,item_id) references public.inventory_items(tenant_id,id));
create table public.sales(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,status text not null default 'draft' check(status in('draft','completed','cancelled')),subtotal_minor bigint not null default 0,discount_minor bigint not null default 0,total_minor bigint generated always as(subtotal_minor-discount_minor) stored,discount_authorized_by uuid references auth.users(id),request_id uuid not null,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),unique(tenant_id,id),unique(tenant_id,request_id),check(discount_minor>=0 and discount_minor<=subtotal_minor));
create table public.sale_items(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,sale_id uuid not null,item_id uuid not null,quantity integer not null check(quantity>0),unit_minor bigint not null check(unit_minor>=0),foreign key(tenant_id,sale_id) references public.sales(tenant_id,id),foreign key(tenant_id,item_id) references public.inventory_items(tenant_id,id));
alter table public.obligations enable row level security;alter table public.ledger_entries enable row level security;alter table public.ledger_allocations enable row level security;alter table public.inventory_items enable row level security;alter table public.inventory_movements enable row level security;alter table public.sales enable row level security;alter table public.sale_items enable row level security;
revoke all on public.obligations,public.ledger_entries,public.ledger_allocations,public.inventory_items,public.inventory_movements,public.sales,public.sale_items from public,anon,authenticated;grant select on public.obligations,public.ledger_entries,public.ledger_allocations,public.inventory_items,public.inventory_movements,public.sales,public.sale_items to authenticated;
create policy finance_read on public.obligations for select to authenticated using(private.has_role(tenant_id,array['admin']) or (repair_id is not null and private.owns_repair(tenant_id,repair_id)));create policy ledger_read on public.ledger_entries for select to authenticated using(private.has_role(tenant_id,array['admin']));create policy allocations_read on public.ledger_allocations for select to authenticated using(private.has_role(tenant_id,array['admin']));create policy inventory_read on public.inventory_items for select to authenticated using(private.has_role(tenant_id,array['admin','advisor','technician']));create policy movements_read on public.inventory_movements for select to authenticated using(private.has_role(tenant_id,array['admin','advisor','technician']));create policy sales_read on public.sales for select to authenticated using(private.has_role(tenant_id,array['admin','advisor']));create policy sale_items_read on public.sale_items for select to authenticated using(private.has_role(tenant_id,array['admin','advisor']));
create function private.record_payment(p_tenant uuid,p_obligation uuid,p_amount bigint,p_method text,p_reference text,p_request uuid) returns uuid language plpgsql security definer set search_path='' as $$declare v uuid;v_due bigint;begin perform private.assert_write(p_tenant,array['admin'],true);select id into v from public.ledger_entries where tenant_id=p_tenant and request_id=p_request;if found then return v;end if;select o.amount_minor-coalesce(sum(case when e.kind='payment' then a.amount_minor when e.kind='reversal' then -a.amount_minor else 0 end),0) into v_due from public.obligations o left join public.ledger_allocations a on a.tenant_id=o.tenant_id and a.obligation_id=o.id left join public.ledger_entries e on e.tenant_id=a.tenant_id and e.id=a.entry_id where o.tenant_id=p_tenant and o.id=p_obligation and o.status='open' group by o.id;if v_due is null or p_amount<=0 or p_amount>v_due then raise exception 'Invalid payment allocation' using errcode='23514';end if;insert into public.ledger_entries(tenant_id,kind,amount_minor,method,reference,request_id,created_by)values(p_tenant,'payment',p_amount,p_method,p_reference,p_request,auth.uid())returning id into v;insert into public.ledger_allocations(tenant_id,entry_id,obligation_id,amount_minor)values(p_tenant,v,p_obligation,p_amount);if p_amount=v_due then update public.obligations set status='settled' where id=p_obligation;end if;perform private.audit(p_tenant,'payment.recorded',v);return v;end$$;
create function private.move_inventory(p_tenant uuid,p_item uuid,p_kind text,p_quantity integer,p_request uuid,p_repair uuid default null) returns uuid language plpgsql security definer set search_path='' as $$declare i public.inventory_items%rowtype;v uuid;begin perform private.assert_write(p_tenant,array['admin','advisor','technician']);select id into v from public.inventory_movements where tenant_id=p_tenant and request_id=p_request;if found then return v;end if;select * into i from public.inventory_items where tenant_id=p_tenant and id=p_item for update;if not found or p_quantity=0 then raise exception 'Invalid inventory movement' using errcode='23514';end if;if p_kind='receive' then update public.inventory_items set stock=stock+abs(p_quantity),version=version+1 where id=p_item;elsif p_kind='reserve' and i.stock-i.reserved>=abs(p_quantity) then update public.inventory_items set reserved=reserved+abs(p_quantity),version=version+1 where id=p_item;elsif p_kind='release' and i.reserved>=abs(p_quantity) then update public.inventory_items set reserved=reserved-abs(p_quantity),version=version+1 where id=p_item;elsif p_kind='consume' and i.reserved>=abs(p_quantity) then update public.inventory_items set reserved=reserved-abs(p_quantity),stock=stock-abs(p_quantity),version=version+1 where id=p_item;else raise exception 'Insufficient or invalid stock' using errcode='23514';end if;insert into public.inventory_movements(tenant_id,item_id,kind,quantity,request_id,repair_id,created_by)values(p_tenant,p_item,p_kind,p_quantity,p_request,p_repair,auth.uid())returning id into v;perform private.audit(p_tenant,'inventory.'||p_kind,v);return v;end$$;
create function public.record_payment(uuid,uuid,bigint,text,text,uuid) returns uuid language sql security invoker set search_path='' as $$select private.record_payment($1,$2,$3,$4,$5,$6)$$;create function public.move_inventory(uuid,uuid,text,integer,uuid,uuid default null) returns uuid language sql security invoker set search_path='' as $$select private.move_inventory($1,$2,$3,$4,$5,$6)$$;
revoke all on function private.record_payment(uuid,uuid,bigint,text,text,uuid),private.move_inventory(uuid,uuid,text,integer,uuid,uuid),public.record_payment(uuid,uuid,bigint,text,text,uuid),public.move_inventory(uuid,uuid,text,integer,uuid,uuid) from public,anon;grant execute on function private.record_payment(uuid,uuid,bigint,text,text,uuid),private.move_inventory(uuid,uuid,text,integer,uuid,uuid),public.record_payment(uuid,uuid,bigint,text,text,uuid),public.move_inventory(uuid,uuid,text,integer,uuid,uuid) to authenticated;
commit;
