begin;
-- F08: a customer request creates an order request, never physical custody or an intake voucher.
create function private.create_customer_repair_request(p_tenant uuid,p_device text,p_issue text,p_request_id uuid) returns uuid language plpgsql security definer set search_path='' as $$declare v uuid;v_customer uuid;v_existing public.repairs%rowtype;begin
 perform private.assert_write(p_tenant,array['customer']);
 select id into v_customer from public.customers where tenant_id=p_tenant and user_id=auth.uid() order by created_at limit 1;
 if v_customer is null then raise exception 'Customer profile unavailable' using errcode='42501';end if;
 insert into public.repairs(tenant_id,customer_id,device,issue,created_by,request_id)values(p_tenant,v_customer,trim(p_device),trim(p_issue),auth.uid(),p_request_id)on conflict(tenant_id,request_id)do nothing returning id into v;
 if v is null then select * into strict v_existing from public.repairs where tenant_id=p_tenant and request_id=p_request_id;if v_existing.customer_id<>v_customer or v_existing.device<>trim(p_device) or v_existing.issue<>trim(p_issue) then raise exception 'Idempotency conflict' using errcode='23505';end if;return v_existing.id;end if;
 insert into public.repair_events(tenant_id,repair_id,status,actor_id)values(p_tenant,v,'created',auth.uid());perform private.audit(p_tenant,'repair.requested_by_customer',v);insert into private.outbox(tenant_id,event_type,aggregate_id)values(p_tenant,'repair.requested',v);return v;end$$;
create function public.create_customer_repair_request(p_tenant uuid,p_device text,p_issue text,p_request_id uuid) returns uuid language sql security invoker set search_path='' as $$select private.create_customer_repair_request(p_tenant,p_device,p_issue,p_request_id)$$;
revoke all on function private.create_customer_repair_request(uuid,text,text,uuid),public.create_customer_repair_request(uuid,text,text,uuid) from public,anon;grant execute on function private.create_customer_repair_request(uuid,text,text,uuid),public.create_customer_repair_request(uuid,text,text,uuid) to authenticated;

-- F19: delivery is a separate auditable fact and requires passed QA and no open balance.
create table public.delivery_events(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,repair_id uuid not null,recipient_name text not null,notes text not null default '',operation_id uuid not null,confirmed_by uuid not null references auth.users(id),confirmed_at timestamptz not null default now(),unique(tenant_id,repair_id),unique(tenant_id,operation_id),foreign key(tenant_id,repair_id) references public.repairs(tenant_id,id));
alter table public.delivery_events enable row level security;revoke all on public.delivery_events from public,anon,authenticated;grant select on public.delivery_events to authenticated;create policy delivery_read on public.delivery_events for select to authenticated using(private.can_read_repair(tenant_id,repair_id));
create function private.confirm_delivery(p_tenant uuid,p_repair uuid,p_recipient text,p_notes text,p_operation_id uuid) returns uuid language plpgsql security definer set search_path='' as $$declare v uuid;begin perform private.assert_write(p_tenant,array['admin']);select id into v from public.delivery_events where tenant_id=p_tenant and operation_id=p_operation_id;if found then return v;end if;if not exists(select 1 from public.qa_runs where tenant_id=p_tenant and repair_id=p_repair and status='passed') then raise exception 'Passed QA required' using errcode='23514';end if;if exists(select 1 from public.obligations where tenant_id=p_tenant and repair_id=p_repair and status='open') then raise exception 'Open balance prevents delivery' using errcode='23514';end if;insert into public.delivery_events(tenant_id,repair_id,recipient_name,notes,operation_id,confirmed_by)values(p_tenant,p_repair,trim(p_recipient),trim(p_notes),p_operation_id,auth.uid())returning id into v;perform private.audit(p_tenant,'delivery.confirmed',v);insert into private.outbox(tenant_id,event_type,aggregate_id)values(p_tenant,'delivery.confirmed',v);return v;end$$;
create function public.confirm_delivery(p_tenant uuid,p_repair uuid,p_recipient text,p_notes text,p_operation_id uuid) returns uuid language sql security invoker set search_path='' as $$select private.confirm_delivery(p_tenant,p_repair,p_recipient,p_notes,p_operation_id)$$;
revoke all on function private.confirm_delivery(uuid,uuid,text,text,uuid),public.confirm_delivery(uuid,uuid,text,text,uuid) from public,anon;grant execute on function private.confirm_delivery(uuid,uuid,text,text,uuid),public.confirm_delivery(uuid,uuid,text,text,uuid) to authenticated;
commit;
