begin;
-- P17/P18: an intent is not proof of delivery; outbox consumers are idempotent.
create table public.message_templates(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,code text not null,channel text not null check(channel in('whatsapp_link','in_app')),body text not null,active boolean not null default true,unique(tenant_id,code));
create table public.conversations(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,repair_id uuid,audience text not null check(audience in('customer','staff')),created_at timestamptz not null default now(),unique(tenant_id,id));
create table public.messages(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,conversation_id uuid not null,author_id uuid not null references auth.users(id),body text not null,status text not null default 'created' check(status in('created','queued','processed','failed')),request_id uuid not null,created_at timestamptz not null default now(),unique(tenant_id,request_id),foreign key(tenant_id,conversation_id) references public.conversations(tenant_id,id));
create table private.outbox_deliveries(id uuid primary key default gen_random_uuid(),outbox_id uuid not null references private.outbox(id),consumer text not null,status text not null check(status in('processing','processed','failed')),attempts integer not null default 0,last_error text,updated_at timestamptz not null default now(),unique(outbox_id,consumer));
-- P19/P20: versioned SaaS commercial facts and explicit operational restrictions.
create table public.plan_versions(id uuid primary key default gen_random_uuid(),plan_code text not null references public.plans(code),version integer not null,entitlements jsonb not null,price_minor bigint,currency text not null default 'COP',effective_from timestamptz not null,unique(plan_code,version));
create table public.billing_cycles(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,plan_version_id uuid not null references public.plan_versions(id),period_start timestamptz not null,period_end timestamptz not null,status text not null check(status in('open','paid','past_due','void')),unique(tenant_id,period_start));
create table public.saas_charges(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,billing_cycle_id uuid not null references public.billing_cycles(id),amount_minor bigint not null check(amount_minor>=0),currency text not null default 'COP',kind text not null check(kind in('subscription','courtesy')),created_at timestamptz not null default now());
create table public.saas_payments(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,billing_cycle_id uuid not null references public.billing_cycles(id),amount_minor bigint not null check(amount_minor>0),method text not null,reference text,request_id uuid not null,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),unique(tenant_id,request_id));
create table public.tenant_restrictions(tenant_id uuid primary key references public.tenants(id),mode text not null check(mode in('none','read_only','suspended')),reason text not null,allowed_routes text[] not null default array['/billing','/support'],updated_at timestamptz not null default now(),updated_by uuid not null references auth.users(id));
-- P21/P22: exported facts and richer audit envelope.
create table public.export_jobs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,kind text not null,filters jsonb not null default '{}',status text not null default 'queued' check(status in('queued','running','ready','failed')),storage_path text,created_by uuid not null references auth.users(id),created_at timestamptz not null default now());
alter table public.audit_events add column if not exists reason text,add column if not exists resource_type text,add column if not exists operation_id uuid,add column if not exists redacted_diff jsonb not null default '{}'::jsonb;
alter table public.message_templates enable row level security;alter table public.conversations enable row level security;alter table public.messages enable row level security;alter table public.plan_versions enable row level security;alter table public.billing_cycles enable row level security;alter table public.saas_charges enable row level security;alter table public.saas_payments enable row level security;alter table public.tenant_restrictions enable row level security;alter table public.export_jobs enable row level security;alter table private.outbox_deliveries enable row level security;
revoke all on public.message_templates,public.conversations,public.messages,public.plan_versions,public.billing_cycles,public.saas_charges,public.saas_payments,public.tenant_restrictions,public.export_jobs from public,anon,authenticated;revoke all on private.outbox_deliveries from public,anon,authenticated;grant select on public.message_templates,public.conversations,public.messages,public.plan_versions,public.billing_cycles,public.saas_charges,public.saas_payments,public.tenant_restrictions,public.export_jobs to authenticated;
create policy message_templates_read on public.message_templates for select to authenticated using(private.has_role(tenant_id,array['admin','advisor','technician']));create policy conversations_read on public.conversations for select to authenticated using((repair_id is not null and private.can_read_repair(tenant_id,repair_id)) or private.has_role(tenant_id,array['admin','advisor']));create policy messages_read on public.messages for select to authenticated using(exists(select 1 from public.conversations c where c.tenant_id=messages.tenant_id and c.id=messages.conversation_id and ((c.repair_id is not null and private.can_read_repair(c.tenant_id,c.repair_id)) or private.has_role(c.tenant_id,array['admin','advisor']))));create policy plan_versions_read on public.plan_versions for select to authenticated using(auth.uid() is not null);create policy cycles_read on public.billing_cycles for select to authenticated using(private.has_role(tenant_id,array['admin']));create policy charges_read on public.saas_charges for select to authenticated using(private.has_role(tenant_id,array['admin']));create policy saas_payments_read on public.saas_payments for select to authenticated using(private.has_role(tenant_id,array['admin']));create policy restrictions_read on public.tenant_restrictions for select to authenticated using(private.has_role(tenant_id,array['admin','advisor','technician','customer']));create policy exports_read on public.export_jobs for select to authenticated using(private.has_role(tenant_id,array['admin']));
create view public.tenant_kpis with(security_invoker=true) as select r.tenant_id,count(*) repair_count,count(*) filter(where r.status='completed') completed_count,count(*) filter(where r.status<>'completed') open_count from public.repairs r group by r.tenant_id;
grant select on public.tenant_kpis to authenticated;
create function private.enqueue_message(p_tenant uuid,p_conversation uuid,p_body text,p_request uuid) returns uuid language plpgsql security definer set search_path='' as $$declare v uuid;begin perform private.assert_write(p_tenant,array['admin','advisor','technician']);select id into v from public.messages where tenant_id=p_tenant and request_id=p_request;if found then return v;end if;insert into public.messages(tenant_id,conversation_id,author_id,body,request_id)values(p_tenant,p_conversation,auth.uid(),trim(p_body),p_request)returning id into v;insert into private.outbox(tenant_id,event_type,aggregate_id,payload)values(p_tenant,'message.created',v,jsonb_build_object('conversation_id',p_conversation));perform private.audit(p_tenant,'message.created',v);return v;end$$;
create function private.set_tenant_restriction(p_tenant uuid,p_mode text,p_reason text) returns void language plpgsql security definer set search_path='' as $$begin if not private.is_platform_admin() then raise exception 'Access denied' using errcode='42501';end if;insert into public.tenant_restrictions(tenant_id,mode,reason,updated_by)values(p_tenant,p_mode,p_reason,auth.uid())on conflict(tenant_id)do update set mode=excluded.mode,reason=excluded.reason,updated_at=now(),updated_by=auth.uid();perform private.audit(p_tenant,'tenant.restriction_changed',p_tenant,jsonb_build_object('mode',p_mode));end$$;
create function public.enqueue_message(uuid,uuid,text,uuid) returns uuid language sql security invoker set search_path='' as $$select private.enqueue_message($1,$2,$3,$4)$$;create function public.set_tenant_restriction(uuid,text,text) returns void language sql security invoker set search_path='' as $$select private.set_tenant_restriction($1,$2,$3)$$;
revoke all on function private.enqueue_message(uuid,uuid,text,uuid),private.set_tenant_restriction(uuid,text,text),public.enqueue_message(uuid,uuid,text,uuid),public.set_tenant_restriction(uuid,text,text) from public,anon;grant execute on function private.enqueue_message(uuid,uuid,text,uuid),private.set_tenant_restriction(uuid,text,text),public.enqueue_message(uuid,uuid,text,uuid),public.set_tenant_restriction(uuid,text,text) to authenticated;
commit;
