begin;
-- P11: quality control is independent from payment and delivery.
create table public.qa_runs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,repair_id uuid not null,status text not null default 'draft' check(status in('draft','passed','failed')),notes text,created_by uuid not null references auth.users(id),completed_at timestamptz,version integer not null default 1,unique(tenant_id,id),foreign key(tenant_id,repair_id) references public.repairs(tenant_id,id));
create table public.qa_checks(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,qa_run_id uuid not null,label text not null,result text not null check(result in('pass','fail','na')),na_reason text,check(result<>'na' or nullif(trim(na_reason),'') is not null),foreign key(tenant_id,qa_run_id) references public.qa_runs(tenant_id,id));
-- P12: immutable business facts rendered from versioned snapshots.
create table public.document_templates(id uuid primary key default gen_random_uuid(),tenant_id uuid,code text not null,version integer not null,format text not null check(format in('a4','80mm')),body jsonb not null,active boolean not null default true,unique(tenant_id,code,version));
create table public.document_snapshots(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,repair_id uuid,kind text not null,template_code text not null,template_version integer not null,snapshot jsonb not null,schema_version integer not null default 1,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),unique(tenant_id,id));
create table public.render_jobs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,document_id uuid not null,format text not null check(format in('a4','80mm')),status text not null default 'queued' check(status in('queued','rendering','ready','failed')),storage_path text,attempts integer not null default 0,error_code text,created_at timestamptz not null default now(),foreign key(tenant_id,document_id) references public.document_snapshots(tenant_id,id));
alter table public.qa_runs enable row level security;alter table public.qa_checks enable row level security;alter table public.document_templates enable row level security;alter table public.document_snapshots enable row level security;alter table public.render_jobs enable row level security;
revoke all on public.qa_runs,public.qa_checks,public.document_templates,public.document_snapshots,public.render_jobs from public,anon,authenticated;grant select on public.qa_runs,public.qa_checks,public.document_templates,public.document_snapshots,public.render_jobs to authenticated;
create policy qa_runs_read on public.qa_runs for select to authenticated using(private.can_read_repair(tenant_id,repair_id));create policy qa_checks_read on public.qa_checks for select to authenticated using(exists(select 1 from public.qa_runs q where q.tenant_id=qa_checks.tenant_id and q.id=qa_checks.qa_run_id and private.can_read_repair(q.tenant_id,q.repair_id)));create policy templates_read on public.document_templates for select to authenticated using(tenant_id is null or private.has_role(tenant_id,array['admin','advisor','technician']));create policy document_read on public.document_snapshots for select to authenticated using(repair_id is not null and private.can_read_repair(tenant_id,repair_id));create policy render_read on public.render_jobs for select to authenticated using(exists(select 1 from public.document_snapshots d where d.tenant_id=render_jobs.tenant_id and d.id=render_jobs.document_id and private.can_read_repair(d.tenant_id,d.repair_id)));
create function private.complete_qa(p_tenant uuid,p_repair uuid,p_checks jsonb,p_notes text) returns uuid language plpgsql security definer set search_path='' as $$declare v uuid;v_status text;begin perform private.assert_write(p_tenant,array['admin','technician']);if not private.can_read_repair(p_tenant,p_repair) or jsonb_typeof(p_checks)<>'array' or jsonb_array_length(p_checks)=0 then raise exception 'Invalid QA' using errcode='23514';end if;v_status:=case when exists(select 1 from jsonb_array_elements(p_checks)x where x->>'result'='fail') then 'failed' else 'passed' end;insert into public.qa_runs(tenant_id,repair_id,status,notes,created_by,completed_at) values(p_tenant,p_repair,v_status,p_notes,auth.uid(),now()) returning id into v;insert into public.qa_checks(tenant_id,qa_run_id,label,result,na_reason) select p_tenant,v,trim(x->>'label'),x->>'result',x->>'na_reason' from jsonb_array_elements(p_checks)x;if v_status='failed' then update public.repairs set status='in_repair',version=version+1,updated_at=now() where tenant_id=p_tenant and id=p_repair;end if;perform private.audit(p_tenant,'qa.'||v_status,v);return v;end$$;
create function private.snapshot_document(p_tenant uuid,p_repair uuid,p_kind text,p_code text,p_version integer,p_snapshot jsonb,p_format text) returns uuid language plpgsql security definer set search_path='' as $$declare v uuid;begin perform private.assert_write(p_tenant,array['admin','advisor','technician']);if not private.can_read_repair(p_tenant,p_repair) or jsonb_typeof(p_snapshot)<>'object' then raise exception 'Invalid document' using errcode='23514';end if;insert into public.document_snapshots(tenant_id,repair_id,kind,template_code,template_version,snapshot,created_by)values(p_tenant,p_repair,p_kind,p_code,p_version,p_snapshot,auth.uid())returning id into v;insert into public.render_jobs(tenant_id,document_id,format)values(p_tenant,v,p_format);perform private.audit(p_tenant,'document.snapshotted',v);return v;end$$;
create function public.complete_qa(uuid,uuid,jsonb,text) returns uuid language sql security invoker set search_path='' as $$select private.complete_qa($1,$2,$3,$4)$$;create function public.snapshot_document(uuid,uuid,text,text,integer,jsonb,text) returns uuid language sql security invoker set search_path='' as $$select private.snapshot_document($1,$2,$3,$4,$5,$6,$7)$$;
revoke all on function private.complete_qa(uuid,uuid,jsonb,text),private.snapshot_document(uuid,uuid,text,text,integer,jsonb,text),public.complete_qa(uuid,uuid,jsonb,text),public.snapshot_document(uuid,uuid,text,text,integer,jsonb,text) from public,anon;grant execute on function private.complete_qa(uuid,uuid,jsonb,text),private.snapshot_document(uuid,uuid,text,text,integer,jsonb,text),public.complete_qa(uuid,uuid,jsonb,text),public.snapshot_document(uuid,uuid,text,text,integer,jsonb,text) to authenticated;
commit;
